/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_grimpirate_SVGWall */

#ifndef _Included_com_grimpirate_SVGWall
#define _Included_com_grimpirate_SVGWall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_grimpirate_SVGWall
 * Method:    apply
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_grimpirate_SVGWall_apply
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
