#!/bin/sh

DIR="$(dirname "$(readlink -f "${0}")")"
LIBS="
rhino-1.8.0
picocli-4.7.7
xmlgraphics-commons-2.11
batik-anim-1.19
batik-bridge-1.19
batik-css-1.19
batik-dom-1.19
batik-gvt-1.19
batik-transcoder-1.19
batik-util-1.19
batik-i18n-1.19
batik-svg-dom-1.19
batik-constants-1.19
batik-ext-1.19
batik-xml-1.19
batik-parser-1.19
batik-script-1.19
batik-awt-util-1.19
xml-apis-ext-1.3.04
"

CLASSPATH=""

for JAR in $LIBS; do
	CLASSPATH="$CLASSPATH:$DIR/../lib/$JAR.jar"
done

exec "$DIR/jre/bin/svgwall" \
	-Dawt.useSystemAAFontSettings=on \
	-Dswing.aatext=true \
	-Dfile.encoding=UTF-8 \
	-Dstdout.encoding=UTF-8 \
	-Dstderr.encoding=UTF-8 \
	-Djava.library.path="$DIR/../lib" \
	-classpath "$DIR$CLASSPATH" \
	com.grimpirate.SVGWall \
	-p "$DIR/x11root" \
	-m "$DIR/../share/metainfo/com.grimpirate.svgwall.appdata.xml" \
	"$@"
