#!/bin/sh

DIR="$(dirname "$(readlink -f "${0}")")"
LIBS="
rhino-1.7.15
picocli-4.7.6
xmlgraphics-commons-2.9
batik-anim-1.17
batik-bridge-1.17
batik-css-1.17
batik-dom-1.17
batik-gvt-1.17
batik-transcoder-1.17
batik-util-1.17
batik-i18n-1.17
batik-svg-dom-1.17
batik-constants-1.17
batik-ext-1.17
batik-xml-1.17
batik-parser-1.17
batik-script-1.17
batik-awt-util-1.17
xml-apis-ext-1.3.04
"

CLASSPATH=""

for JAR in $LIBS; do
	CLASSPATH="$CLASSPATH:$DIR/../lib/$JAR.jar"
done

exec "$DIR/jre/bin/svgwall" \
	-Dawt.useSystemAAFontSettings=on \
	-Dswing.aatext=true \
	-Dfile.encoding=UTF-8 \
	-Dstdout.encoding=UTF-8 \
	-Dstderr.encoding=UTF-8 \
	-Djava.library.path="$DIR/../lib" \
	-classpath "$DIR$CLASSPATH" \
	com.grimpirate.SVGWall \
	-m "$DIR/../share/metainfo/svgwall.appdata.xml" \
	"$@"